"""Add excluded_from_regular_awards to User model and enhance BonanzaTransaction audit fields

Revision ID: 6788fb5871ab
Revises: 922400f2f0a6
Create Date: 2025-09-14 09:54:45.443135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6788fb5871ab'
down_revision = '922400f2f0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping table that doesn't exist
    # op.drop_table('_alembic_tmp_transaction')
    with op.batch_alter_table('bonanza_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_count', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('previous_count', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('new_count', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('required_target', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('achieved', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_bonanza_transaction_source_transaction_id', 'transaction', ['source_transaction_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluded_from_regular_awards', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('excluded_from_regular_awards')

    with op.batch_alter_table('bonanza_transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bonanza_transaction_source_transaction_id', type_='foreignkey')
        batch_op.drop_column('achieved')
        batch_op.drop_column('required_target')
        batch_op.drop_column('new_count')
        batch_op.drop_column('previous_count')
        batch_op.drop_column('activity_count')
        batch_op.drop_column('source_transaction_id')

    op.create_table('_alembic_tmp_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sponsor_id', sa.INTEGER(), nullable=False),
    sa.Column('referred_user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), server_default=sa.text("'Direct Referral'"), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('referral_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('referral_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_type', 'referral_id'),
    sa.UniqueConstraint('referral_type', 'referral_id', 'transaction_type', name=op.f('unique_referral_payout'))
    )
    # ### end Alembic commands ###
