"""Add password reset and user management fields

Revision ID: 922400f2f0a6
Revises: cb3576968f27
Create Date: 2025-09-14 09:03:11.015009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922400f2f0a6'
down_revision = 'cb3576968f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('unique_referral_payout', ['referral_type', 'referral_id', 'transaction_type'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=20), nullable=False, server_default='Active'))

    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_withdrawal_user_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_withdrawal_user_date'), ['user_id', 'request_date'], unique=1)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_status')
        batch_op.drop_column('last_login')
        batch_op.drop_column('password_reset_expires')
        batch_op.drop_column('password_reset_token')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('unique_referral_payout', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
