"""Add secondary_password field to User model for Super Admin enhanced security

Revision ID: b4199b547061
Revises: 11ca5309302f
Create Date: 2025-09-15 12:20:45.270758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4199b547061'
down_revision = '11ca5309302f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_entity_created', ['entity_type', 'entity_id', 'created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_password', sa.String(length=255), nullable=True))
        batch_op.alter_column('earned_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('released_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_index(batch_op.f('ix_user_serial_number'))
        batch_op.drop_index(batch_op.f('ix_user_unique_member_id'))
        batch_op.create_index('idx_user_account_status', ['account_status'], unique=False)
        batch_op.create_index('idx_user_computed_totals', ['earned_total', 'released_total'], unique=False)
        batch_op.create_index('idx_user_is_ved', ['is_ved'], unique=False)
        batch_op.create_index('idx_user_kyc_status', ['kyc_status'], unique=False)
        batch_op.create_index('idx_user_placement_status', ['placement_status'], unique=False)
        batch_op.create_index('idx_user_referrer_id', ['referrer_id'], unique=False)
        batch_op.create_index('idx_user_registration_date', ['registration_date'], unique=False)
        batch_op.create_index('idx_user_unique_member_id', ['unique_member_id'], unique=False)

    with op.batch_alter_table('user_package', schema=None) as batch_op:
        batch_op.create_index('idx_user_package_user_updated', ['user_id', 'updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_package', schema=None) as batch_op:
        batch_op.drop_index('idx_user_package_user_updated')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_unique_member_id')
        batch_op.drop_index('idx_user_registration_date')
        batch_op.drop_index('idx_user_referrer_id')
        batch_op.drop_index('idx_user_placement_status')
        batch_op.drop_index('idx_user_kyc_status')
        batch_op.drop_index('idx_user_is_ved')
        batch_op.drop_index('idx_user_computed_totals')
        batch_op.drop_index('idx_user_account_status')
        batch_op.create_index(batch_op.f('ix_user_unique_member_id'), ['unique_member_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_serial_number'), ['serial_number'], unique=1)
        batch_op.alter_column('released_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('earned_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_column('secondary_password')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_log_entity_created')

    # ### end Alembic commands ###
