"""Add normalized placement table with proper constraints

Revision ID: be12742b322d
Revises: dee4cc221460
Create Date: 2025-09-14 14:37:30.088105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be12742b322d'
down_revision = 'dee4cc221460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_serial_number'))
        batch_op.drop_index(batch_op.f('ix_user_unique_member_id'))
        batch_op.create_index('idx_placement_position_left', ['left_child'], unique=True, postgresql_where=sa.text('left_child IS NOT NULL'))
        batch_op.create_index('idx_placement_position_right', ['right_child'], unique=True, postgresql_where=sa.text('right_child IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_placement_position_right', postgresql_where=sa.text('right_child IS NOT NULL'))
        batch_op.drop_index('idx_placement_position_left', postgresql_where=sa.text('left_child IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_user_unique_member_id'), ['unique_member_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_user_serial_number'), ['serial_number'], unique=1)

    # ### end Alembic commands ###
