"""Add EV and Purchase models for EV purchase system

Revision ID: cb3576968f27
Revises: ccc9dc170018
Create Date: 2025-09-14 07:55:30.559980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3576968f27'
down_revision = 'ccc9dc170018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Try to drop constraint if it exists - handle gracefully if it doesn't
    try:
        with op.batch_alter_table('transaction', schema=None) as batch_op:
            batch_op.drop_constraint('uq_txn_event', type_='unique')
    except Exception:
        # Constraint doesn't exist - continue silently
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_txn_event'), ['sponsor_id', 'referred_user_id', 'transaction_type'])

    # ### end Alembic commands ###
