"""Add unique constraint for bonanza transaction idempotency

Revision ID: dee4cc221460
Revises: 6788fb5871ab
Create Date: 2025-09-14 10:12:23.552519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee4cc221460'
down_revision = '6788fb5871ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonanza_transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_bonanza_transaction_idempotency', ['bonanza_id', 'user_id', 'source_transaction_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonanza_transaction', schema=None) as batch_op:
        batch_op.drop_constraint('unique_bonanza_transaction_idempotency', type_='unique')

    # ### end Alembic commands ###
