"""
Canonical Location Ingestion Service
Phase 6 Step 1: Consolidated Canonical Location Ingestion Correctness & Hardening
================================================================================
Authoritative, concurrency-safe single-point ingestion for GPS observations across
Staff Journeys and Staff Realtime Telemetry.

Key Correctness Contracts:
1. Canonical Physical Observation Identity:
   - Modern clients provide UUIDv4 client_observation_id.
   - Validated strictly (parsed_uuid.version == 4); malformed/non-v4 IDs rejected with 400 error.
   - Legacy clients omitting client_observation_id generate a deterministic UUIDv5 legacy
     deduplication fingerprint: UUIDv5(NAMESPACE_URL, f"geo:{employee_id}:{lat:.6f}:{lng:.6f}:{captured_at_iso}").
   - Modern UUIDv4 identity takes precedence; coordinate/time fallback never collapses modern observations.
2. Strict Timestamp Semantics:
   - captured_at = Physical observation capture time from sensor.
   - server_received_at = Backend ingestion timestamp generated by server.
   - Invalid supplied timestamps are rejected with 400 error (NEVER silently coerced to server time).
   - Missing timestamps default to server time only for legacy compatibility when omitted.
3. Accurate Physical Telemetry:
   - Negative altitudes are preserved without artificial clamping.
   - Dual-tier validation: Telemetry <= 500m max accuracy; WVV Journey reimbursement <= 100m.
4. Concurrency & Idempotency:
   - Row-level locking (with_for_update) on StaffJourney within PostgreSQL transaction.
   - Replay/retry idempotency returns existing record without duplicate insertion.
   - Distinct modern observations at stationary coordinates are both recorded.
5. Out-of-Order Processing & Memory Safety:
   - Chronological recalculation scoped strictly to the individual journey_id.
   - Preserves historical monotonicity without unbounded memory overhead.
6. Financial Immutability:
   - If journey approval_status in [APPROVED, AUTO_APPROVED] or status == CANCELLED:
     Track points are saved for visual/route audit trail, but total_distance_km,
     reimbursable_distance_km, and reimbursement_amount remain strictly frozen.
"""

import logging
import math
import uuid
from datetime import datetime, timezone
from typing import Optional, Dict, Any, Tuple, List
import pytz

from fastapi import HTTPException, Request
from sqlalchemy.orm import Session
from sqlalchemy import func, and_, or_
from sqlalchemy.exc import IntegrityError

from app.models.staff_journey import (
    StaffJourney, StaffJourneyTrackPoint, JourneyStatus, JourneyApprovalStatus
)
from app.models.staff_attendance import (
    StaffAttendance, StaffRealtimeLocation, StaffAttendanceBreak,
    generate_realtime_dc_code, get_indian_time, get_indian_date
)
from app.models.staff import StaffEmployee

logger = logging.getLogger(__name__)

IST = pytz.timezone('Asia/Kolkata')
WVV_MAX_ACCURACY_METERS = 100.0
MAX_TELEMETRY_ACCURACY_METERS = 500.0


class LocationIngestionService:
    """
    Authoritative ingestion service for all GPS telemetry and journey track points.
    """

    @staticmethod
    def generate_legacy_dedup_fingerprint(
        employee_id: int,
        latitude: float,
        longitude: float,
        captured_at: datetime
    ) -> str:
        """
        Generate deterministic UUIDv5 fallback fingerprint strictly for legacy deduplication.
        Domain-agnostic: Never includes journey_id or attendance_id.
        Formula: UUIDv5(NAMESPACE_URL, f"geo:{employee_id}:{latitude:.6f}:{longitude:.6f}:{iso_ts}")
        """
        iso_str = captured_at.isoformat() if isinstance(captured_at, datetime) else str(captured_at)
        raw_identity = f"geo:{employee_id}:{latitude:.6f}:{longitude:.6f}:{iso_str}"
        return str(uuid.uuid5(uuid.NAMESPACE_URL, raw_identity))

    @classmethod
    def normalize_observation(
        cls,
        raw_data: Dict[str, Any],
        employee_id: int
    ) -> Dict[str, Any]:
        """
        Parse, validate, and normalize a raw GPS observation into a canonical dictionary.
        Enforces strict UUIDv4 identity validation and non-coercive timestamp parsing.
        """
        if not raw_data:
            raise HTTPException(status_code=400, detail="GPS location data is required")

        # Extract coordinates
        lat_val = raw_data.get('latitude') if raw_data.get('latitude') is not None else raw_data.get('lat')
        lng_val = raw_data.get('longitude') if raw_data.get('longitude') is not None else raw_data.get('lng')

        if lat_val is None or lng_val is None:
            raise HTTPException(status_code=400, detail="GPS Error: latitude and longitude are required")

        try:
            latitude = float(lat_val)
            longitude = float(lng_val)
        except (ValueError, TypeError):
            raise HTTPException(status_code=400, detail="GPS Error: invalid coordinate format")

        if not (-90.0 <= latitude <= 90.0) or not (-180.0 <= longitude <= 180.0):
            raise HTTPException(
                status_code=400,
                detail=f"GPS Error: coordinates out of range (lat: {latitude}, lng: {longitude})"
            )

        # Accuracy validation
        acc_val = raw_data.get('accuracy_m') if raw_data.get('accuracy_m') is not None else raw_data.get('accuracy')
        accuracy_m = None
        if acc_val is not None:
            try:
                accuracy_m = float(acc_val)
                if accuracy_m <= 0:
                    raise HTTPException(status_code=400, detail="GPS Error: accuracy must be greater than 0")
            except (ValueError, TypeError):
                raise HTTPException(status_code=400, detail="GPS Error: invalid accuracy value")

        # Altitude preservation (do not artificially clamp negative altitudes)
        alt_val = raw_data.get('altitude')
        altitude = None
        if alt_val is not None:
            try:
                altitude = float(alt_val)
            except (ValueError, TypeError):
                altitude = None

        # Speed (support speed in m/s or speed_kmh)
        speed_kmh = None
        if raw_data.get('speed_kmh') is not None:
            try:
                speed_kmh = float(raw_data.get('speed_kmh'))
            except (ValueError, TypeError):
                speed_kmh = None
        elif raw_data.get('speed') is not None:
            try:
                speed_kmh = float(raw_data.get('speed')) * 3.6
            except (ValueError, TypeError):
                speed_kmh = None

        # Heading
        heading = None
        if raw_data.get('heading') is not None:
            try:
                heading = float(raw_data.get('heading'))
            except (ValueError, TypeError):
                heading = None

        # Battery percentage
        battery_pct = None
        if raw_data.get('battery_percentage') is not None:
            try:
                battery_pct = int(raw_data.get('battery_percentage'))
            except (ValueError, TypeError):
                battery_pct = None
        elif raw_data.get('battery_level') is not None:
            try:
                battery_pct = int(float(raw_data.get('battery_level')))
            except (ValueError, TypeError):
                battery_pct = None

        # Address & Source
        address = raw_data.get('address')
        source = raw_data.get('source', 'heartbeat')

        # Captured At timestamp parsing (strict: NEVER silently coerce invalid timestamp to server time)
        captured_at = None
        raw_ts = raw_data.get('captured_at') if raw_data.get('captured_at') is not None else raw_data.get('timestamp')
        if raw_ts is not None:
            if isinstance(raw_ts, datetime):
                captured_at = raw_ts.replace(tzinfo=None) if raw_ts.tzinfo else raw_ts
            elif isinstance(raw_ts, (int, float)):
                try:
                    if raw_ts > 1e11:  # Milliseconds
                        captured_at = datetime.fromtimestamp(raw_ts / 1000.0, tz=timezone.utc).astimezone(IST).replace(tzinfo=None)
                    else:
                        captured_at = datetime.fromtimestamp(raw_ts, tz=timezone.utc).astimezone(IST).replace(tzinfo=None)
                except Exception as e:
                    raise HTTPException(status_code=400, detail=f"Invalid GPS timestamp epoch value '{raw_ts}': {e}")
            elif isinstance(raw_ts, str):
                if not raw_ts.strip():
                    raise HTTPException(status_code=400, detail="Empty GPS timestamp string provided")
                try:
                    ts_clean = raw_ts.strip().replace('Z', '+00:00')
                    dt_parsed = datetime.fromisoformat(ts_clean)
                    if dt_parsed.tzinfo:
                        captured_at = dt_parsed.astimezone(IST).replace(tzinfo=None)
                    else:
                        captured_at = dt_parsed
                except Exception as e:
                    raise HTTPException(status_code=400, detail=f"Invalid ISO GPS timestamp format '{raw_ts}': {e}")
            else:
                raise HTTPException(status_code=400, detail=f"Unsupported GPS timestamp format: {type(raw_ts)}")
        else:
            # Omitted timestamp: Fall back to current server time for legacy compatibility
            captured_at = get_indian_time()

        # Client Observation ID validation
        raw_obs_id = raw_data.get('client_observation_id')
        client_obs_id = None
        is_legacy = False

        if raw_obs_id is not None:
            if not isinstance(raw_obs_id, str):
                raise HTTPException(status_code=400, detail="client_observation_id must be a string UUIDv4")
            cleaned_id = raw_obs_id.strip()
            if not cleaned_id:
                raise HTTPException(status_code=400, detail="client_observation_id cannot be empty")
            try:
                parsed_uuid = uuid.UUID(cleaned_id)
            except (ValueError, TypeError, AttributeError):
                raise HTTPException(status_code=400, detail=f"Malformed client_observation_id '{cleaned_id}': not a valid UUID")

            if parsed_uuid.version != 4:
                raise HTTPException(
                    status_code=400,
                    detail=f"Invalid client_observation_id version: expected UUIDv4, got UUIDv{parsed_uuid.version}"
                )
            client_obs_id = str(parsed_uuid)
        else:
            # Legacy client fallback: generate deterministic UUIDv5 legacy deduplication fingerprint
            is_legacy = True
            client_obs_id = cls.generate_legacy_dedup_fingerprint(
                employee_id=employee_id,
                latitude=latitude,
                longitude=longitude,
                captured_at=captured_at
            )

        server_received_at = get_indian_time()

        return {
            "client_observation_id": client_obs_id,
            "is_legacy": is_legacy,
            "latitude": latitude,
            "longitude": longitude,
            "accuracy_m": accuracy_m,
            "altitude": altitude,
            "speed_kmh": speed_kmh,
            "heading": heading,
            "battery_percentage": battery_pct,
            "address": address,
            "source": source,
            "captured_at": captured_at,
            "server_received_at": server_received_at
        }

    @classmethod
    def ingest_journey_track_point(
        cls,
        db: Session,
        journey_id: int,
        employee_id: int,
        observation_data: Dict[str, Any],
        http_request: Optional[Request] = None
    ) -> Dict[str, Any]:
        """
        Ingest GPS observation into StaffJourneyTrackPoint.
        - Locks StaffJourney row with_for_update() (concurrency safe).
        - Idempotent deduplication by client_observation_id (or legacy coordinate/timestamp fallback).
        - Recalculates distances chronologically if out-of-order arrival (bounded per journey).
        - Honors financial immutability if journey is approved/finalized.
        """
        # Concurrency safety: Row-level lock on journey
        query = db.query(StaffJourney).filter(
            StaffJourney.id == journey_id,
            StaffJourney.employee_id == employee_id
        )
        if db.bind and db.bind.dialect.name != 'sqlite':
            query = query.with_for_update()

        journey = query.first()
        if not journey:
            raise HTTPException(status_code=404, detail="Journey not found")

        # Normalize observation
        obs = cls.normalize_observation(observation_data, employee_id)
        accuracy_m = obs['accuracy_m']

        # WVV Compliance check (accuracy <= 100m is compliant for journey reimbursement)
        wvv_compliant = accuracy_m is not None and accuracy_m <= WVV_MAX_ACCURACY_METERS
        wvv_reason = None
        if not wvv_compliant:
            if accuracy_m is None:
                wvv_reason = "GPS accuracy not available"
            else:
                wvv_reason = f"GPS accuracy ({accuracy_m:.0f}m) exceeds WVV threshold ({WVV_MAX_ACCURACY_METERS:.0f}m)"

        # Idempotency / Duplicate Check
        if not obs["is_legacy"]:
            # Modern client: Match STRICTLY by client_observation_id
            existing_point = db.query(StaffJourneyTrackPoint).filter(
                StaffJourneyTrackPoint.journey_id == journey_id,
                StaffJourneyTrackPoint.client_observation_id == obs['client_observation_id']
            ).first()
        else:
            # Legacy client: Match by client_observation_id (UUIDv5) OR coordinate + timestamp
            existing_point = db.query(StaffJourneyTrackPoint).filter(
                StaffJourneyTrackPoint.journey_id == journey_id,
                or_(
                    StaffJourneyTrackPoint.client_observation_id == obs['client_observation_id'],
                    and_(
                        StaffJourneyTrackPoint.latitude == obs['latitude'],
                        StaffJourneyTrackPoint.longitude == obs['longitude'],
                        StaffJourneyTrackPoint.timestamp == obs['captured_at']
                    )
                )
            ).first()

        if existing_point:
            return {
                "success": True,
                "duplicate": True,
                "message": "Track point already recorded (idempotent duplicate response)",
                "track_point_id": existing_point.id,
                "client_observation_id": existing_point.client_observation_id,
                "distance_km": round(journey.total_distance_km or 0, 2),
                "reimbursable_distance_km": round(journey.reimbursable_distance_km or 0, 2),
                "current_speed_kmh": round(obs['speed_kmh'], 1) if obs['speed_kmh'] else 0,
                "max_speed_kmh": round(journey.max_speed_kmh or 0, 1),
                "reimbursement_amount": journey.reimbursement_amount if journey.is_reimbursable else 0,
                "wvv_compliant": existing_point.wvv_compliant,
                "wvv_reason": existing_point.compliance_reason
            }

        # Check latest recorded point for chronological order
        last_point = db.query(StaffJourneyTrackPoint).filter(
            StaffJourneyTrackPoint.journey_id == journey_id
        ).order_by(StaffJourneyTrackPoint.timestamp.desc(), StaffJourneyTrackPoint.id.desc()).first()

        is_out_of_order = bool(last_point and obs['captured_at'] < last_point.timestamp)

        # Create new track point
        new_point = StaffJourneyTrackPoint(
            journey_id=journey_id,
            latitude=obs['latitude'],
            longitude=obs['longitude'],
            accuracy=accuracy_m,
            altitude=obs['altitude'],
            speed_kmh=obs['speed_kmh'],
            heading=obs['heading'],
            wvv_compliant=wvv_compliant,
            compliance_reason=wvv_reason,
            address=obs['address'],
            timestamp=obs['captured_at'],
            client_observation_id=obs['client_observation_id'],
            server_received_at=obs['server_received_at'],
            distance_from_prev=0.0,
            cumulative_distance=0.0
        )
        db.add(new_point)

        # Distance calculation
        cumulative_distance = 0.0
        reimbursable_distance = 0.0

        if is_out_of_order:
            # Out-of-order point arrived: Re-evaluate chronologically across points of this journey
            db.flush()  # assign ID to new_point
            all_points = db.query(StaffJourneyTrackPoint).filter(
                StaffJourneyTrackPoint.journey_id == journey_id
            ).order_by(StaffJourneyTrackPoint.timestamp.asc(), StaffJourneyTrackPoint.id.asc()).all()

            cum_dist = 0.0
            reimb_dist = 0.0
            prev_p = None
            for p in all_points:
                if prev_p is None:
                    p.distance_from_prev = 0.0
                    p.cumulative_distance = 0.0
                else:
                    d = StaffJourneyTrackPoint.haversine_distance(
                        prev_p.latitude, prev_p.longitude,
                        p.latitude, p.longitude
                    )
                    cum_dist += d
                    p.distance_from_prev = d
                    p.cumulative_distance = cum_dist
                    if p.wvv_compliant and prev_p.wvv_compliant:
                        reimb_dist += d
                prev_p = p

            cumulative_distance = cum_dist
            reimbursable_distance = reimb_dist
        else:
            # In-order arrival
            distance_from_prev = 0.0
            if last_point:
                distance_from_prev = StaffJourneyTrackPoint.haversine_distance(
                    last_point.latitude, last_point.longitude,
                    obs['latitude'], obs['longitude']
                )
                cumulative_distance = (last_point.cumulative_distance or 0.0) + distance_from_prev
                if wvv_compliant and last_point.wvv_compliant:
                    reimbursable_distance = (journey.reimbursable_distance_km or 0.0) + distance_from_prev
                else:
                    reimbursable_distance = journey.reimbursable_distance_km or 0.0
            else:
                cumulative_distance = 0.0
                reimbursable_distance = 0.0

            new_point.distance_from_prev = distance_from_prev
            new_point.cumulative_distance = cumulative_distance

        # Financial Immutability Rule:
        # If journey has already been APPROVED or AUTO_APPROVED, or CANCELLED, do NOT alter financial or distance totals!
        is_financial_locked = (
            journey.approval_status in [JourneyApprovalStatus.APPROVED, JourneyApprovalStatus.AUTO_APPROVED] or
            journey.status == JourneyStatus.CANCELLED
        )

        if not is_financial_locked:
            journey.total_distance_km = cumulative_distance
            if obs['speed_kmh'] and (journey.max_speed_kmh is None or obs['speed_kmh'] > journey.max_speed_kmh):
                journey.max_speed_kmh = obs['speed_kmh']

            if journey.is_reimbursable:
                journey.reimbursable_distance_km = reimbursable_distance
                journey.calculate_reimbursement()
        else:
            logger.info(
                f"[LOCATION_INGEST_FROZEN] Journey {journey_id} is financially locked ({journey.approval_status}/{journey.status}). "
                f"Track point recorded for visual audit trail without mutating financial totals."
            )

        db.commit()
        db.refresh(new_point)

        return {
            "success": True,
            "duplicate": False,
            "track_point_id": new_point.id,
            "client_observation_id": new_point.client_observation_id,
            "distance_km": round(journey.total_distance_km or 0, 2),
            "reimbursable_distance_km": round(journey.reimbursable_distance_km or 0, 2),
            "current_speed_kmh": round(obs['speed_kmh'], 1) if obs['speed_kmh'] else 0,
            "max_speed_kmh": round(journey.max_speed_kmh or 0, 1),
            "reimbursement_amount": journey.reimbursement_amount if journey.is_reimbursable else 0,
            "wvv_compliant": wvv_compliant,
            "wvv_reason": wvv_reason,
            "wvv_accuracy_m": round(accuracy_m, 0) if accuracy_m else None
        }

    @classmethod
    def ingest_realtime_location(
        cls,
        db: Session,
        employee_id: int,
        observation_data: Dict[str, Any],
        request: Optional[Request] = None
    ) -> Dict[str, Any]:
        """
        Ingest continuous telemetry into StaffRealtimeLocation.
        - Validates dual-tier accuracy (max 500m for telemetry, 100m for WVV).
        - Idempotent deduplication by client_observation_id.
        - Updates active attendance GPS metadata (last_gps_at, gps_status, worked_minutes).
        """
        obs = cls.normalize_observation(observation_data, employee_id)
        accuracy_m = obs['accuracy_m']

        if accuracy_m is None:
            raise HTTPException(status_code=400, detail="GPS Error: accuracy is required for telemetry")

        if accuracy_m > MAX_TELEMETRY_ACCURACY_METERS:
            raise HTTPException(
                status_code=400,
                detail=f"GPS Rejected: Accuracy {accuracy_m:.0f}m exceeds maximum {MAX_TELEMETRY_ACCURACY_METERS:.0f}m limit."
            )

        is_wvv_compliant = accuracy_m <= WVV_MAX_ACCURACY_METERS

        now = get_indian_time()
        today = get_indian_date()

        # Employee lookup
        employee = db.query(StaffEmployee).filter(StaffEmployee.id == employee_id).first()
        emp_code = employee.emp_code if employee else f"EMP{employee_id}"

        # Get today's attendance
        attendance = db.query(StaffAttendance).filter(
            StaffAttendance.employee_id == employee_id,
            StaffAttendance.date == today
        ).first()

        # Check if on break
        active_break = None
        if attendance:
            active_break = db.query(StaffAttendanceBreak).filter(
                StaffAttendanceBreak.attendance_id == attendance.id,
                StaffAttendanceBreak.break_end == None
            ).first()

        # Check if on journey
        active_journey = db.query(StaffJourney).filter(
            StaffJourney.employee_id == employee_id,
            StaffJourney.status == JourneyStatus.IN_PROGRESS
        ).first()

        # Generate DC Code (for display / legacy audit purposes)
        dc_code = generate_realtime_dc_code(emp_code, now)

        # Deduplication check
        if not obs["is_legacy"]:
            # Modern client: Match strictly by client_observation_id
            existing_loc = db.query(StaffRealtimeLocation).filter(
                StaffRealtimeLocation.employee_id == employee_id,
                StaffRealtimeLocation.client_observation_id == obs['client_observation_id']
            ).first()
        else:
            # Legacy client: Match by client_observation_id (UUIDv5) OR dc_code
            existing_loc = db.query(StaffRealtimeLocation).filter(
                StaffRealtimeLocation.employee_id == employee_id,
                or_(
                    StaffRealtimeLocation.client_observation_id == obs['client_observation_id'],
                    StaffRealtimeLocation.dc_code == dc_code
                )
            ).first()

        if existing_loc:
            return {
                "success": True,
                "duplicate": True,
                "message": "Realtime location already recorded (idempotent duplicate response)",
                "location_id": existing_loc.id,
                "client_observation_id": existing_loc.client_observation_id,
                "dc_code": existing_loc.dc_code,
                "is_wvv_compliant": is_wvv_compliant,
                "worked_minutes": attendance.worked_minutes if attendance else 0
            }

        # Device info
        device_info_data = {
            "user_agent": request.headers.get("User-Agent", "") if request else "",
            "is_wvv_compliant": is_wvv_compliant,
            "accuracy_quality": "high" if accuracy_m <= 50 else ("medium" if accuracy_m <= 100 else ("low" if accuracy_m <= 300 else "degraded"))
        }
        if obs['battery_percentage'] is not None:
            device_info_data["battery_percentage"] = obs['battery_percentage']

        app_version = request.headers.get("X-App-Version", None) if request else None
        app_platform = request.headers.get("X-App-Platform", None) if request else None
        client_ip = request.client.host if request and request.client else None

        location = StaffRealtimeLocation(
            employee_id=employee_id,
            latitude=obs['latitude'],
            longitude=obs['longitude'],
            accuracy_m=accuracy_m,
            altitude=obs['altitude'],
            speed_kmh=obs['speed_kmh'],
            heading=obs['heading'],
            source=obs['source'],
            attendance_id=attendance.id if attendance else None,
            journey_id=active_journey.id if active_journey else None,
            is_clocked_in=attendance is not None and attendance.clock_out is None,
            is_on_break=active_break is not None,
            is_on_journey=active_journey is not None,
            break_type=active_break.break_type.upper() if active_break and active_break.break_type else None,
            dc_code=dc_code,
            device_info=device_info_data,
            ip_address=client_ip,
            user_agent=request.headers.get("User-Agent", "") if request else "",
            app_version=app_version,
            app_platform=app_platform,
            captured_at=obs['captured_at'],
            client_observation_id=obs['client_observation_id'],
            server_received_at=obs['server_received_at']
        )
        db.add(location)

        # Update attendance tracking status
        if attendance:
            # Physical GPS observation timestamp
            attendance.last_gps_at = obs['captured_at']
            attendance.gps_status = 'active'
            attendance.gps_status_reason = None
            attendance.gps_status_at = now
            if obs['battery_percentage'] is not None:
                attendance.last_battery_pct = obs['battery_percentage']

            # Calculate worked_minutes based on attendance clock_in to now
            if attendance.clock_in and not attendance.clock_out:
                total_break_mins = db.query(func.coalesce(func.sum(StaffAttendanceBreak.duration_minutes), 0)).filter(
                    StaffAttendanceBreak.attendance_id == attendance.id
                ).scalar() or 0
                attendance.break_minutes = int(total_break_mins)
                elapsed_seconds = (now - attendance.clock_in).total_seconds()
                attendance.worked_minutes = max(0, int(elapsed_seconds / 60) - attendance.break_minutes)

        try:
            db.commit()
            db.refresh(location)
        except IntegrityError:
            db.rollback()
            # Race condition handling: Check if location exists
            existing_loc = db.query(StaffRealtimeLocation).filter(
                StaffRealtimeLocation.employee_id == employee_id,
                or_(
                    StaffRealtimeLocation.client_observation_id == obs['client_observation_id'],
                    StaffRealtimeLocation.dc_code == dc_code
                )
            ).first()
            if existing_loc:
                return {
                    "success": True,
                    "duplicate": True,
                    "message": "Realtime location already recorded (idempotent duplicate response)",
                    "location_id": existing_loc.id,
                    "client_observation_id": existing_loc.client_observation_id,
                    "dc_code": existing_loc.dc_code,
                    "is_wvv_compliant": is_wvv_compliant,
                    "worked_minutes": attendance.worked_minutes if attendance else 0
                }
            raise

        return {
            "success": True,
            "duplicate": False,
            "location_id": location.id,
            "client_observation_id": location.client_observation_id,
            "dc_code": location.dc_code,
            "is_wvv_compliant": is_wvv_compliant,
            "worked_minutes": attendance.worked_minutes if attendance else 0,
            "server_received_at": location.server_received_at.isoformat() if location.server_received_at else None
        }
