"use client";

import React from "react";
import Link from "next/link";

export default function GuruEarningsPage() {
  const stats = {
    totalGuruEarning: 25000,
    activeMentees: 4,
    highestEarner: "Rahul Sharma"
  };

  const mentees = [
    { id: 'VGK00214', name: 'Rahul Sharma', level: 'Direct (Level 1)', theirIncome: 225000, guruShare: 11250 },
    { id: 'VGK00388', name: 'Priya Desai', level: 'Direct (Level 1)', theirIncome: 0, guruShare: 0 },
    { id: 'VGK00441', name: 'Anita Patel', level: 'Direct (Level 1)', theirIncome: 275000, guruShare: 13750 },
  ];

  return (
    <div className="p-6 max-w-7xl mx-auto flex flex-col h-[calc(100vh-80px)]">
      <div className="flex justify-between items-end mb-6 shrink-0">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 tracking-tight">Guru Dakshina Earnings</h1>
          <p className="text-sm text-gray-500 mt-2">Earn 5% of the total income generated by your direct downlines as a mentorship bonus.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 shrink-0">
        <div className="bg-gradient-to-br from-indigo-900 to-purple-900 p-6 rounded-xl shadow-lg flex items-center justify-between text-white relative overflow-hidden">
          <i className="fas fa-chalkboard-teacher absolute right-[-20px] bottom-[-20px] text-8xl opacity-10"></i>
          <div className="relative z-10">
            <p className="text-xs font-bold text-indigo-200 uppercase tracking-wider mb-1">Total Guru Earnings</p>
            <div className="flex items-baseline gap-2 mb-2">
              <span className="text-2xl font-medium text-indigo-200">₹</span>
              <h3 className="text-4xl font-bold text-white">{stats.totalGuruEarning.toLocaleString('en-IN')}</h3>
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex items-center gap-4">
          <div className="w-14 h-14 bg-indigo-50 text-indigo-600 rounded-full flex items-center justify-center text-2xl shrink-0">
            <i className="fas fa-user-graduate"></i>
          </div>
          <div>
            <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Active Mentees</p>
            <h3 className="text-3xl font-bold text-gray-900">{stats.activeMentees}</h3>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex items-center gap-4">
          <div className="w-14 h-14 bg-amber-50 text-amber-600 rounded-full flex items-center justify-center text-2xl shrink-0">
            <i className="fas fa-medal"></i>
          </div>
          <div>
            <p className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Top Performing Mentee</p>
            <h3 className="text-xl font-bold text-gray-900 truncate">{stats.highestEarner}</h3>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-100 flex-1 overflow-hidden flex flex-col min-h-0">
        <div className="p-4 border-b border-gray-200 bg-gray-50 flex justify-between items-center">
          <h3 className="font-bold text-gray-900">Mentee Earnings Breakdown</h3>
          <button className="text-sm font-medium text-indigo-600 hover:text-indigo-800">
            How it works?
          </button>
        </div>

        <div className="flex-1 overflow-auto p-0">
          <table className="w-full text-left">
            <thead className="bg-white sticky top-0 z-10">
              <tr className="border-b border-gray-200">
                <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Mentee Name</th>
                <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Relationship</th>
                <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Their Total Income</th>
                <th className="p-4 text-xs font-bold text-gray-500 uppercase tracking-wider text-right bg-indigo-50/50">Your 5% Share</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {mentees.map((mentee, idx) => (
                <tr key={idx} className="hover:bg-gray-50 transition-colors">
                  <td className="p-4">
                    <p className="font-bold text-gray-900">{mentee.name}</p>
                    <p className="text-xs text-gray-500 font-mono">{mentee.id}</p>
                  </td>
                  <td className="p-4 text-sm text-gray-600">
                    <span className="bg-blue-50 text-blue-700 text-xs font-bold px-2 py-1 rounded">{mentee.level}</span>
                  </td>
                  <td className="p-4 text-right">
                    <span className="font-bold text-gray-700">₹ {mentee.theirIncome.toLocaleString('en-IN')}</span>
                  </td>
                  <td className="p-4 text-right bg-indigo-50/30">
                    <span className={`font-bold ${mentee.guruShare > 0 ? 'text-indigo-600' : 'text-gray-400'}`}>
                      + ₹ {mentee.guruShare.toLocaleString('en-IN')}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
