"""
Pydantic Schemas for Staff KRA Performance Management System
DC Protocol Compliant - Validation at every entry point

Request/Response schemas for:
- KRA Templates (with approval workflow)
- KRA Assignments (with SPOC/Manager)
- Daily KRA Instances (task tracking)
- Performance Summaries (metrics)

Created: Nov 26, 2025
DC Protocol: Write-Verify-Validate at all levels
"""

from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Optional, List, Dict, Any, Union
from datetime import date, datetime, time
from enum import Enum


# Enums for validation
class ApprovalStatus(str, Enum):
    DRAFT = "draft"
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    REJECTED = "rejected"


class FrequencyType(str, Enum):
    DAILY = "daily"
    EVERY_N_DAYS = "every_n_days"
    SELECTED_DAYS = "selected_days"
    EVERY_15_DAYS = "every_15_days"
    MONTHLY = "monthly"
    CUSTOM = "custom"
    ADHOC = "adhoc"


class CompletionStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    PARTIAL = "partial"
    SKIPPED = "skipped"
    NA = "na"  # Not Applicable / Exempted - DC Protocol: Exempt from calculations


class TimeSource(str, Enum):
    MANUAL = "manual"
    TIME_TRACKER = "time_tracker"
    HYBRID = "hybrid"


class SummaryPeriod(str, Enum):
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"


class RecordStatus(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    REMOVED = "removed"


class ManagerReviewStatus(str, Enum):
    """Manager review workflow statuses"""
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    EDITED_BY_MANAGER = "edited_by_manager"
    REJECTED = "rejected"


# ==================== KRA TEMPLATE SCHEMAS ====================

class FrequencyConfigBase(BaseModel):
    """Base frequency configuration"""
    pattern: str
    
    model_config = {"extra": "forbid"}  # Reject unknown fields for DC Protocol compliance


class DailyFrequencyConfig(FrequencyConfigBase):
    """Daily frequency - every working day"""
    pattern: str = "daily"


class EveryNDaysConfig(FrequencyConfigBase):
    """Every N days frequency"""
    pattern: str = "every_n_days"
    interval: int = Field(..., ge=1, le=90, description="Days interval (1-90)")


class SelectedDaysConfig(FrequencyConfigBase):
    """Selected days frequency - any combination of 7 days"""
    pattern: str = "selected_days"
    days: List[str] = Field(..., min_length=1, max_length=7)
    
    @field_validator('days')
    @classmethod
    def validate_days(cls, v):
        valid_days = {'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'}
        for day in v:
            if day.lower() not in valid_days:
                raise ValueError(f'Invalid day: {day}. Must be one of {valid_days}')
        return [day.lower() for day in v]


class MonthlyConfig(FrequencyConfigBase):
    """Monthly frequency - specific day of month"""
    pattern: str = "monthly"
    day_of_month: int = Field(..., ge=1, le=31, description="Day of month (1-31)")


class CustomConfig(FrequencyConfigBase):
    """Custom frequency - specific dates in month"""
    pattern: str = "custom"
    dates: List[int] = Field(..., min_length=1, description="Day numbers in month")
    
    @field_validator('dates')
    @classmethod
    def validate_dates(cls, v):
        for d in v:
            if not 1 <= d <= 31:
                raise ValueError(f'Invalid date: {d}. Must be between 1-31')
        return sorted(list(set(v)))  # Remove duplicates and sort


class Every15DaysConfig(FrequencyConfigBase):
    """Every 15 days frequency"""
    pattern: str = "every_15_days"


class AdhocConfig(FrequencyConfigBase):
    """Ad-hoc frequency - manual assignment only"""
    pattern: str = "adhoc"


# Type Union for frequency_config - DC Protocol compliance
FrequencyConfigUnion = Union[
    DailyFrequencyConfig,
    EveryNDaysConfig,
    SelectedDaysConfig,
    MonthlyConfig,
    CustomConfig,
    Every15DaysConfig,
    AdhocConfig,
    None
]


class KRATemplateCreate(BaseModel):
    """Schema for creating KRA template"""
    kra_code: Optional[str] = Field(None, max_length=32, description="Auto-generated by server if not provided")
    title: str = Field(..., min_length=5, max_length=256)
    description: Optional[str] = None
    applicable_to_role: Optional[str] = Field(None, max_length=64)
    applicable_to_designation: Optional[str] = Field(None, max_length=128)
    frequency: FrequencyType
    frequency_config: Optional[Dict[str, Any]] = None
    estimated_time_minutes: Optional[int] = Field(None, ge=1, le=480)
    target_time: Optional[str] = Field(None, pattern=r'^\d{2}:\d{2}$', description="Target completion time in HH:MM format (24hr)")
    is_mandatory: bool = True
    
    model_config = {"use_enum_values": True}
    
    @model_validator(mode='after')
    def validate_frequency_config(self):
        """Validate frequency_config matches frequency type"""
        frequency = self.frequency
        v = self.frequency_config
        
        if not frequency:
            return self
        
        # ADHOC requires no config
        if frequency == FrequencyType.ADHOC or frequency == 'adhoc':
            if v and v.get('pattern') != 'adhoc':
                raise ValueError('Ad-hoc frequency should have pattern="adhoc" or no config')
            self.frequency_config = v or {'pattern': 'adhoc'}
            return self
        
        # All other frequencies require config
        if not v:
            raise ValueError(f'{frequency} frequency requires frequency_config')
        
        pattern = v.get('pattern')
        
        if frequency == FrequencyType.DAILY or frequency == 'daily':
            if pattern != 'daily':
                raise ValueError('Daily frequency must have pattern="daily"')
        
        elif frequency == FrequencyType.EVERY_N_DAYS or frequency == 'every_n_days':
            if pattern != 'every_n_days':
                raise ValueError('Every N days frequency must have pattern="every_n_days"')
            interval = v.get('interval')
            if not interval or not (1 <= interval <= 90):
                raise ValueError('Every N days requires interval between 1-90')
        
        elif frequency == FrequencyType.SELECTED_DAYS or frequency == 'selected_days':
            if pattern != 'selected_days':
                raise ValueError('Selected days frequency must have pattern="selected_days"')
            days = v.get('days', [])
            if not days or len(days) < 1:
                raise ValueError('Selected days requires at least 1 day')
            valid_days = {'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'}
            normalized_days = []
            for day in days:
                day_lower = day.lower()
                if day_lower not in valid_days:
                    raise ValueError(f'Invalid day: {day}')
                normalized_days.append(day_lower)
            v['days'] = list(set(normalized_days))
        
        elif frequency == FrequencyType.EVERY_15_DAYS or frequency == 'every_15_days':
            if pattern != 'every_15_days':
                raise ValueError('Every 15 days frequency must have pattern="every_15_days"')
        
        elif frequency == FrequencyType.MONTHLY or frequency == 'monthly':
            if pattern != 'monthly':
                raise ValueError('Monthly frequency must have pattern="monthly"')
            day_of_month = v.get('day_of_month')
            if not day_of_month or not (1 <= day_of_month <= 31):
                raise ValueError('Monthly requires day_of_month between 1-31')
        
        elif frequency == FrequencyType.CUSTOM or frequency == 'custom':
            if pattern != 'custom':
                raise ValueError('Custom frequency must have pattern="custom"')
            dates = v.get('dates', [])
            if not dates:
                raise ValueError('Custom frequency requires dates array')
            v['dates'] = sorted(list(set(dates)))
        
        return self


class KRATemplateUpdate(BaseModel):
    """Schema for updating KRA template"""
    title: Optional[str] = Field(None, min_length=5, max_length=256)
    description: Optional[str] = None
    applicable_to_role: Optional[str] = Field(None, max_length=64)
    applicable_to_designation: Optional[str] = Field(None, max_length=128)
    frequency: Optional[FrequencyType] = None
    frequency_config: Optional[Dict[str, Any]] = None
    estimated_time_minutes: Optional[int] = Field(None, ge=1, le=480)
    target_time: Optional[str] = Field(None, pattern=r'^\d{2}:\d{2}$', description="Target completion time in HH:MM format (24hr)")
    is_mandatory: Optional[bool] = None
    status: Optional[RecordStatus] = None
    
    model_config = {"use_enum_values": True}
    
    @model_validator(mode='after')
    def validate_frequency_consistency(self):
        """Ensure frequency and frequency_config are consistent when updating"""
        frequency = self.frequency
        frequency_config = self.frequency_config
        
        if frequency and frequency_config:
            pattern = frequency_config.get('pattern')
            
            if (frequency == FrequencyType.DAILY or frequency == 'daily') and pattern != 'daily':
                raise ValueError('Daily frequency must have pattern="daily"')
            elif (frequency == FrequencyType.EVERY_N_DAYS or frequency == 'every_n_days') and pattern != 'every_n_days':
                raise ValueError('Every N days must have pattern="every_n_days"')
            elif (frequency == FrequencyType.SELECTED_DAYS or frequency == 'selected_days') and pattern != 'selected_days':
                raise ValueError('Selected days must have pattern="selected_days"')
            elif (frequency == FrequencyType.EVERY_15_DAYS or frequency == 'every_15_days') and pattern != 'every_15_days':
                raise ValueError('Every 15 days must have pattern="every_15_days"')
            elif (frequency == FrequencyType.MONTHLY or frequency == 'monthly') and pattern != 'monthly':
                raise ValueError('Monthly must have pattern="monthly"')
            elif (frequency == FrequencyType.CUSTOM or frequency == 'custom') and pattern != 'custom':
                raise ValueError('Custom must have pattern="custom"')
            elif (frequency == FrequencyType.ADHOC or frequency == 'adhoc') and pattern != 'adhoc':
                raise ValueError('Ad-hoc must have pattern="adhoc"')
        
        return self


class KRATemplateApprove(BaseModel):
    """Schema for approving KRA template"""
    notes: Optional[str] = Field(None, max_length=500)


class KRATemplateReject(BaseModel):
    """Schema for rejecting KRA template"""
    reason: str = Field(..., min_length=10, max_length=500)


class KRATemplateResponse(BaseModel):
    """Response schema for KRA template (DC Compliant)"""
    id: int
    kra_code: str
    title: str
    description: Optional[str]
    applicable_to_role: Optional[str]
    applicable_to_designation: Optional[str]
    frequency: str
    frequency_config: Optional[Dict[str, Any]]
    estimated_time_minutes: Optional[int]
    target_time: Optional[str] = None
    is_mandatory: bool
    approval_status: str
    created_by_employee_id: int
    approved_by_employee_id: Optional[int]
    approval_date: Optional[datetime]
    rejection_reason: Optional[str]
    status: str
    created_at: datetime
    updated_at: datetime
    # DC Protocol: Added for Assigned Employees display in KRA Templates list
    assigned_count: int = 0
    assigned_employee_names: List[str] = []
    
    model_config = {"from_attributes": True}


# ==================== KRA ASSIGNMENT SCHEMAS ====================

class KRAAssignmentCreate(BaseModel):
    """Schema for creating KRA assignment - DC Protocol Compliant"""
    employee_id: str = Field(..., pattern=r'^(MR|MN)\d{5}$', description="Employee code (e.g., MR00001, MN10003)")
    kra_template_id: int = Field(..., gt=0)
    primary_spoc_employee_id: str = Field(..., pattern=r'^(MR|MN)\d{5}$', description="SPOC employee code")
    reporting_manager_id: Optional[str] = Field(None, pattern=r'^(MR|MN)\d{5}$', description="Manager employee code")
    assigned_by_employee_id: int = Field(..., gt=0, description="Internal employee ID of assigner (auto-filled)")
    effective_from: date
    effective_until: Optional[date] = None
    
    @model_validator(mode='after')
    def validate_effective_dates(self):
        """Ensure effective_until is after effective_from"""
        if self.effective_until and self.effective_from:
            if self.effective_until < self.effective_from:
                raise ValueError('effective_until must be after effective_from')
        return self


class KRAAssignmentUpdate(BaseModel):
    """Schema for updating KRA assignment"""
    primary_spoc_employee_id: Optional[str] = Field(None, pattern=r'^(MR|MN)\d{5}$')
    reporting_manager_id: Optional[str] = Field(None, pattern=r'^(MR|MN)\d{5}$')
    effective_until: Optional[date] = None
    status: Optional[RecordStatus] = None
    
    model_config = {"use_enum_values": True}


class KRAAssignmentResponse(BaseModel):
    """Response schema for KRA assignment (DC Compliant)"""
    id: int
    employee_id: int
    kra_template_id: int
    primary_spoc_employee_id: int
    reporting_manager_id: Optional[int]
    assigned_by_employee_id: int
    assigned_date: date
    effective_from: date
    effective_until: Optional[date]
    status: str
    created_at: datetime
    
    kra_template: Optional[KRATemplateResponse] = None
    
    model_config = {"from_attributes": True}


# ==================== DAILY KRA INSTANCE SCHEMAS ====================

class DailyKRAInstanceUpdate(BaseModel):
    """Schema for updating daily KRA instance (staff updates) - DC Compliant with defaults"""
    completion_status: CompletionStatus
    completion_percentage: Optional[int] = Field(default=100, ge=0, le=100)
    time_spent_minutes: Optional[int] = Field(None, ge=0, le=1440, description="Time spent in minutes (optional — omit for status-only updates, preserves existing value)")
    time_source: Optional[str] = Field(default="manual", min_length=1, max_length=50)
    staff_notes: Optional[str] = Field(None, max_length=1000)
    
    model_config = {"use_enum_values": True}


class BulkDailyKRAUpdateItem(BaseModel):
    """Single item in bulk KRA update"""
    instance_id: int = Field(..., gt=0)
    completion_status: CompletionStatus
    completion_percentage: int = Field(..., ge=0, le=100)
    time_spent_minutes: int = Field(..., ge=0, le=1440)
    time_source: TimeSource
    staff_notes: Optional[str] = Field(None, max_length=1000)
    
    model_config = {"use_enum_values": True}


class BulkDailyKRAUpdate(BaseModel):
    """Schema for bulk updating multiple KRAs"""
    updates: List[BulkDailyKRAUpdateItem] = Field(..., min_length=1, max_length=50)


class DailyKRAInstanceResponse(BaseModel):
    """Response schema for daily KRA instance (DC Compliant)"""
    id: int
    employee_id: int
    kra_assignment_id: int
    kra_template_id: int
    instance_date: date
    completion_status: str
    completion_percentage: int
    time_spent_minutes: int
    time_source: Optional[str]
    staff_notes: Optional[str]
    completed_at: Optional[datetime]
    
    # Manager Review Fields
    manager_review_status: str
    manager_reviewed_by_employee_id: Optional[int] = None
    manager_review_date: Optional[datetime] = None
    manager_edit_notes: Optional[str] = None
    rejection_reason: Optional[str] = None
    original_values: Optional[Dict[str, Any]] = None
    
    created_at: datetime
    updated_at: datetime
    
    kra_template: Optional[KRATemplateResponse] = None
    
    model_config = {"from_attributes": True}


# ==================== PERFORMANCE SUMMARY SCHEMAS ====================

class PerformanceFilterParams(BaseModel):
    """Query params for performance tracking with dynamic date filters"""
    employee_id: Optional[str] = Field(None, pattern=r'^(MR|MN)\d{5}$')
    summary_period: Optional[SummaryPeriod] = None
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    
    model_config = {"use_enum_values": True}
    
    @model_validator(mode='after')
    def validate_date_range(self):
        """Ensure end_date is after start_date"""
        if self.end_date and self.start_date:
            if self.end_date < self.start_date:
                raise ValueError('end_date must be after start_date')
        return self


class PerformanceSummaryResponse(BaseModel):
    """Response schema for performance summary (DC Compliant)"""
    id: int
    employee_id: int
    summary_period: str
    period_start_date: date
    period_end_date: date
    total_kras_assigned: int
    total_kras_completed: int
    total_kras_partial: int
    total_kras_pending: int
    achievement_percentage: float
    total_time_spent_minutes: int
    total_work_time_minutes: int
    time_utilization_percentage: float
    performance_score: float
    created_at: datetime
    
    model_config = {"from_attributes": True}


# ==================== AUDIT LOG SCHEMAS ====================

class AuditLogResponse(BaseModel):
    """Response schema for audit log (DC Compliant)"""
    id: int
    record_type: str
    record_id: int
    action: str
    old_data: Optional[Dict[str, Any]]
    new_data: Optional[Dict[str, Any]]
    changed_by_employee_id: Optional[int]
    ip_address: Optional[str]
    user_agent: Optional[str]
    created_at: datetime
    
    model_config = {"from_attributes": True}


# ==================== LIST/FILTER RESPONSE SCHEMAS ====================

class KRATemplateListResponse(BaseModel):
    """Paginated list of KRA templates"""
    templates: List[KRATemplateResponse]
    total: int
    page: int
    per_page: int
    total_pages: int


class PaginatedKRATemplates(BaseModel):
    """Paginated list of KRA templates (alias)"""
    total: int
    page: int
    page_size: int
    templates: List[KRATemplateResponse]


class PaginatedKRAAssignments(BaseModel):
    """Paginated list of KRA assignments"""
    total: int
    page: int
    page_size: int
    assignments: List[KRAAssignmentResponse]


class PaginatedDailyKRAs(BaseModel):
    """Paginated list of daily KRA instances"""
    total: int
    page: int
    page_size: int
    instances: List[DailyKRAInstanceResponse]


class PerformanceDashboardResponse(BaseModel):
    """Complete performance dashboard with dynamic filters - DC Protocol Compliant"""
    employee_id: int
    employee_mnr_id: Optional[str] = None
    period_start: date
    period_end: date
    summary_period: str
    metrics: PerformanceSummaryResponse
    daily_instances: List[DailyKRAInstanceResponse]
    active_assignments: List[KRAAssignmentResponse]


# ==================== MANAGER REVIEW SCHEMAS ====================

class ManagerApproveKRARequest(BaseModel):
    """Request to approve a KRA daily instance"""
    instance_id: int = Field(..., gt=0)
    notes: Optional[str] = Field(None, max_length=1000)
    
    model_config = {"extra": "forbid"}


class ManagerEditKRARequest(BaseModel):
    """Request to edit and auto-approve a KRA daily instance"""
    instance_id: int = Field(..., gt=0)
    completion_status: Optional[str] = Field(None, min_length=1, max_length=32, pattern=r'^[a-z0-9_]+$', description="Must match configurable status codes")
    completion_percentage: Optional[int] = Field(None, ge=0, le=100)
    time_spent_minutes: Optional[int] = Field(None, ge=0)
    staff_notes: Optional[str] = Field(None, max_length=2000)
    manager_edit_notes: str = Field(..., min_length=1, max_length=1000, description="Reason for edit (required)")
    
    model_config = {"extra": "forbid"}
    
    @model_validator(mode='after')
    def validate_at_least_one_edit(self):
        """Ensure at least one field is being edited"""
        if not any([
            self.completion_status is not None,
            self.completion_percentage is not None,
            self.time_spent_minutes is not None,
            self.staff_notes is not None
        ]):
            raise ValueError("At least one field must be edited")
        return self


class ManagerRejectKRARequest(BaseModel):
    """Request to reject a KRA daily instance"""
    instance_id: int = Field(..., gt=0)
    rejection_reason: str = Field(..., min_length=1, max_length=1000)
    
    model_config = {"extra": "forbid"}


class ManagerBulkApproveRequest(BaseModel):
    """Bulk approve multiple KRA instances"""
    instance_ids: List[int] = Field(..., min_length=1, max_length=100)
    notes: Optional[str] = Field(None, max_length=1000)
    
    model_config = {"extra": "forbid"}


class ManagerReviewSummaryResponse(BaseModel):
    """Summary of pending items for manager review"""
    pending_kra_count: int
    pending_task_count: int
    pending_kras: List[DailyKRAInstanceResponse]
    pending_tasks: List[Dict[str, Any]]  # Will be typed properly when task schemas are updated


class ConfigurableStatusCreate(BaseModel):
    """Create a new configurable status"""
    category: str = Field(..., pattern="^(kra|task)$")
    status_code: str = Field(..., min_length=1, max_length=32)
    status_label: str = Field(..., min_length=1, max_length=100)
    status_color: Optional[str] = Field(None, max_length=20)
    counts_for_performance: bool = True
    display_order: int = Field(0, ge=0)
    
    model_config = {"extra": "forbid"}


class ConfigurableStatusUpdate(BaseModel):
    """Update an existing configurable status"""
    status_label: Optional[str] = Field(None, min_length=1, max_length=100)
    status_color: Optional[str] = Field(None, max_length=20)
    counts_for_performance: Optional[bool] = None
    display_order: Optional[int] = Field(None, ge=0)
    status: Optional[str] = Field(None, pattern="^(active|inactive)$")
    
    model_config = {"extra": "forbid"}


class ConfigurableStatusResponse(BaseModel):
    """Response schema for configurable status"""
    id: int
    category: str
    status_code: str
    status_label: str
    status_color: Optional[str]
    counts_for_performance: bool
    is_system_default: bool
    display_order: int
    status: str
    created_by_employee_id: int
    created_at: datetime
    updated_at: datetime
    
    model_config = {"from_attributes": True}
