-- Migration script to add missing columns generated automatically
BEGIN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS deadline_extended BOOLEAN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS extension_count INTEGER;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS activation_completed_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS red_coupon_triggered BOOLEAN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS lockout_applied BOOLEAN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS grace_period_granted BOOLEAN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS grace_period_expires TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS appeal_submitted BOOLEAN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS appeal_approved BOOLEAN;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS admin_notes TEXT;
ALTER TABLE coupon_activation_tracker ADD COLUMN IF NOT EXISTS processed_by_id VARCHAR(12);
ALTER TABLE tds_payable ADD COLUMN IF NOT EXISTS business_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE marketplace_spares ADD COLUMN IF NOT EXISTS stock_item_id INTEGER;
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS base_amount NUMERIC(12, 2);
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS ceiling_applied_amount NUMERIC(12, 2);
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS excess_amount NUMERIC(12, 2);
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS business_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS calculation_timestamp TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS ved_relationship_level INTEGER;
ALTER TABLE ved_income ADD COLUMN IF NOT EXISTS income_percentage NUMERIC(5, 2);
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS can_view_users BOOLEAN;
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS can_edit_users BOOLEAN;
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS can_manage_finances BOOLEAN;
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS can_approve_kyc BOOLEAN;
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS can_manage_bonanza BOOLEAN;
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS can_system_control BOOLEAN;
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(12);
ALTER TABLE custom_roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(12);
ALTER TABLE invoice_line_items ADD COLUMN IF NOT EXISTS hsn_id INTEGER;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS selection_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS effective_from_date DATE;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS scheme_change_count INTEGER;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS last_change_date DATE;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS qualified_for_standard BOOLEAN;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS qualified_for_car BOOLEAN;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS qualification_verified BOOLEAN;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS is_locked BOOLEAN;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS lock_expiry_date DATE;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS lock_reason TEXT;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS admin_override BOOLEAN;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS override_reason TEXT;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS override_by_id VARCHAR(12);
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS override_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS deactivation_reason TEXT;
ALTER TABLE allowance_scheme_selector ADD COLUMN IF NOT EXISTS deactivated_by_id VARCHAR(12);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS business_date TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS direct_referral_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS matching_referral_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS ved_income_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS guru_dakshina_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS admin_deduction_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS tds_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS company_earnings_total NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS gross_payout NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS net_payout NUMERIC(15, 2);
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS total_users_paid INTEGER;
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS calculation_completed_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE daily_cost_calculation ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS variant_name VARCHAR(100);
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS specifications TEXT;
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS approval_status VARCHAR(20);
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS created_by_user_id VARCHAR(12);
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS approved_by_user_id VARCHAR(12);
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE ev_model ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITHOUT TIME ZONE;
COMMIT;
