-- PRODUCTION SQL: Insert all 210 canonical routes
INSERT INTO pdf_canonical_routes (route_path, section_id, section_title, section_order, subsection_title, is_submenu, parent_section, menu_name, menu_icon) VALUES
('/staff/progress', 'progress', 'PROGRESS', 1, NULL, false, NULL, 'Progress Dashboard', 'fas fa-chart-line'),
('/staff/dashboard', 'staff-dashboard', 'STAFF DASHBOARD', 2, NULL, false, NULL, 'Dashboard', 'fas fa-tachometer-alt'),
('/staff/employee-directory', 'staff-dashboard', 'STAFF DASHBOARD', 2, NULL, false, NULL, 'Employee Directory', 'fas fa-address-book'),
('/staff/employees', 'staff-dashboard', 'STAFF DASHBOARD', 2, NULL, false, NULL, 'Employees', 'fas fa-users'),
('/staff/kyc-approvals', 'staff-dashboard', 'STAFF DASHBOARD', 2, NULL, false, NULL, 'KYC Approvals', 'fas fa-check-circle'),
('/staff/manager-review', 'staff-dashboard', 'STAFF DASHBOARD', 2, NULL, false, NULL, 'Review Dashboard', 'fas fa-clipboard-check'),
('/staff/my-kyc', 'staff-dashboard', 'STAFF DASHBOARD', 2, NULL, false, NULL, 'My KYC', 'fas fa-id-card'),
('/staff/attendance-computation', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'Attendance Computation', 'fas fa-calculator'),
('/staff/attendance-exceptions', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'Exception Approvals', 'fas fa-exclamation-circle'),
('/staff/attendance-reports', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'Attendance Dashboard', 'fas fa-chart-bar'),
('/staff/attendance-sheet', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'Attendance Records', 'fas fa-table'),
('/staff/leave-approvals', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'Leave Approvals', 'fas fa-calendar-check'),
('/staff/my-attendance', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'In/Out Time', 'fas fa-clock'),
('/staff/my-leaves', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'My Leaves', 'fas fa-calendar-minus'),
('/staff/team-attendance', 'attendance', 'ATTENDANCE', 3, NULL, false, NULL, 'In/Out Records - Admin', 'fas fa-user-clock'),
('/staff/crm/dashboard', 'crm', 'CRM & LEADS', 4, NULL, false, NULL, 'My CRM Dashboard', 'fas fa-funnel-dollar'),
('/staff/crm/lead-sources', 'crm', 'CRM & LEADS', 4, NULL, false, NULL, 'Lead Sources', 'fas fa-sitemap'),
('/staff/crm/team-leads', 'crm', 'CRM & LEADS', 4, NULL, false, NULL, 'Team Leads', 'fas fa-users-cog'),
('/staff/leads', 'crm', 'CRM & LEADS', 4, NULL, false, NULL, 'Staff Leads', 'fas fa-user-tie'),
('/staff/my-leads', 'crm', 'CRM & LEADS', 4, NULL, false, NULL, 'My Leads', 'fas fa-user-plus'),
('/staff/task-review', 'task-management', 'TASK MANAGEMENT', 5, NULL, false, NULL, 'Task Reviews', 'fas fa-check-double'),
('/staff/tasks/assigned-by-me-v2', 'task-management', 'TASK MANAGEMENT', 5, NULL, false, NULL, 'Assigned By Me', 'fas fa-tasks'),
('/staff/tasks/assigned-to-me', 'task-management', 'TASK MANAGEMENT', 5, NULL, false, NULL, 'Assigned To Me', 'fas fa-clipboard-list'),
('/staff/tasks/team-activities', 'task-management', 'TASK MANAGEMENT', 5, NULL, false, NULL, 'Team Activities', 'fas fa-project-diagram'),
('/staff/tasks/tracker', 'task-management', 'TASK MANAGEMENT', 5, NULL, false, NULL, 'Task Tracker', 'fas fa-chart-gantt'),
('/staff/kra-review', 'kra-management', 'KRA MANAGEMENT', 6, NULL, false, NULL, 'KRA Review', 'fas fa-star-half-alt'),
('/staff/kra-templates', 'kra-management', 'KRA MANAGEMENT', 6, NULL, false, NULL, 'KRA Templates', 'fas fa-file-alt'),
('/staff/kra-tracking-sheet', 'kra-management', 'KRA MANAGEMENT', 6, NULL, false, NULL, 'KRA Tracking Sheet', 'fas fa-table'),
('/staff/my-kras', 'kra-management', 'KRA MANAGEMENT', 6, NULL, false, NULL, 'My KRAs', 'fas fa-bullseye'),
('/staff/my-timesheet', 'timesheet', 'TIMESHEET', 7, NULL, false, NULL, 'My Timesheet', 'fas fa-hourglass-half'),
('/staff/timesheet-approval', 'timesheet', 'TIMESHEET', 7, NULL, false, NULL, 'Timesheet Approval', 'fas fa-check-square'),
('/staff/all-journeys', 'journey-tracking', 'JOURNEY TRACKING', 8, NULL, false, NULL, 'All Journeys', 'fas fa-globe'),
('/staff/my-journeys', 'journey-tracking', 'JOURNEY TRACKING', 8, NULL, false, NULL, 'My Journeys', 'fas fa-route'),
('/staff/team-journeys', 'journey-tracking', 'JOURNEY TRACKING', 8, NULL, false, NULL, 'Team Journeys', 'fas fa-map-marked-alt'),
('/staff/vgk4u-journeys', 'journey-tracking', 'JOURNEY TRACKING', 8, NULL, false, NULL, 'VGK4U Journeys', 'fas fa-car'),
('/staff/my-location-history', 'location-tracking', 'LOCATION TRACKING', 9, NULL, false, NULL, 'My Location History', 'fas fa-map-marker-alt'),
('/staff/team-location-tracker', 'location-tracking', 'LOCATION TRACKING', 9, NULL, false, NULL, 'Team Location Tracker', 'fas fa-map-pin'),
('/staff/accounts/my-reimbursements', 'reimbursement', 'REIMBURSEMENT', 10, NULL, false, NULL, 'My Reimbursement Claims', 'fas fa-receipt'),
('/staff/accounts/reimbursement-approvals', 'reimbursement', 'REIMBURSEMENT', 10, NULL, false, NULL, 'Reimbursement Approvals', 'fas fa-file-invoice-dollar'),
('/staff/service-center-revenue', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Service Center Revenue', 'fas fa-dollar-sign'),
('/staff/service-tickets/dashboard', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Dashboard', 'fas fa-ticket-alt'),
('/staff/service-tickets/performance', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Performance', 'fas fa-chart-line'),
('/staff/service-tickets/procurement', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Procurement', 'fas fa-shopping-cart'),
('/staff/service-tickets/procurement-queue', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Procurement Queue', 'fas fa-list-ol'),
('/staff/service-tickets/queue', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Service Queue', 'fas fa-stream'),
('/staff/service-tickets/raise', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Raise Ticket', 'fas fa-plus-circle'),
('/staff/service-tickets/reports', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Reports', 'fas fa-file-alt'),
('/rvz/sales-revenue', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Sales Team Revenue', 'fas fa-chart-bar'),
('/staff/accounts/balance-sheet', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Balance Sheet', 'fas fa-balance-scale'),
('/staff/accounts/expense-entries', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Expense Entries', 'fas fa-file-invoice'),
('/staff/accounts/fund-allocations', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Fund Allocations', 'fas fa-hand-holding-usd'),
('/staff/accounts/income-entries', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Income Entries', 'fas fa-coins'),
('/staff/accounts/party-ledger', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Party Ledger', 'fas fa-book'),
('/staff/accounts/payables', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Accounts Payable', 'fas fa-money-check-alt'),
('/staff/accounts/purchase-invoices', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Purchase Invoices', 'fas fa-file-alt'),
('/staff/accounts/receivables', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Accounts Receivable', 'fas fa-hand-holding-usd'),
('/staff/accounts/reports', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Invoice Reports', 'fas fa-chart-pie'),
('/staff/accounts/sales-invoices', 'sfms', 'SFMS', 12, 'SFMS', true, 'accounts', 'Sales Invoices', 'fas fa-file-invoice-dollar'),
('/staff/inventory/bom', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Bill of Materials', 'fas fa-clipboard-list'),
('/staff/inventory/intake', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Purchase Intake', 'fas fa-box-open'),
('/staff/inventory/manufacturing', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Manufacturing', 'fas fa-industry'),
('/staff/inventory/procurement', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Procurement', 'fas fa-truck-loading'),
('/staff/inventory/service-center-tracking', 'service-tickets', 'SERVICE TICKETS', 11, NULL, false, NULL, 'Service Center Tracking', 'fas fa-map-marked'),
('/staff/inventory/stock-items', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Stock Items', 'fas fa-boxes'),
('/staff/inventory/stock-ledger', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Stock Ledger', 'fas fa-book'),
('/staff/inventory/stock-transfers', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Stock Transfers', 'fas fa-exchange-alt'),
('/staff/inventory/stock-validation', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Stock Validation', 'fas fa-check-circle'),
('/staff/inventory/vendor-returns', 'inventory', 'Inventory', 12, 'Inventory', true, 'accounts', 'Vendor Returns', 'fas fa-undo'),
('/staff/payroll/allowance-catalog', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Allowance Catalog', 'fas fa-list'),
('/staff/payroll/approvals', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Approvals', 'fas fa-check'),
('/staff/payroll/consultant-invoices', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Consultant Invoices', 'fas fa-file-invoice'),
('/staff/payroll/cycles', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Payroll Cycles', 'fas fa-sync'),
('/staff/payroll/documents', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Documents', 'fas fa-folder-open'),
('/staff/payroll/profiles', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Payroll Profiles', 'fas fa-id-badge'),
('/staff/payroll/runs', 'payroll', 'Payroll', 12, 'Payroll', true, 'accounts', 'Payroll Runs', 'fas fa-play-circle'),
('/staff/partners/approval', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Order Approval', 'fas fa-check-circle'),
('/staff/partners/dispatch', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Dispatch Management', 'fas fa-shipping-fast'),
('/staff/partners/fulfillment', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Order Fulfillment', 'fas fa-truck'),
('/staff/partners/invoices', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Partner Invoices', 'fas fa-file-invoice'),
('/staff/partners/orders', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Partner Orders', 'fas fa-shopping-bag'),
('/staff/partners/payments', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Payment Verification', 'fas fa-credit-card'),
('/staff/partners/pricing', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Partner Pricing', 'fas fa-tags'),
('/staff/partners/routing', 'official-partners', 'BUSINESS PARTNERS', 13, NULL, false, NULL, 'Order Routing', 'fas fa-route'),
('/staff/nda-acceptance-audit', 'nda-management', 'NDA MANAGEMENT', 14, NULL, false, NULL, 'Acceptance Audit', 'fas fa-clipboard-check'),
('/staff/nda-editor', 'nda-management', 'NDA MANAGEMENT', 14, NULL, false, NULL, 'NDA Editor', 'fas fa-edit'),
('/staff/nda-pending', 'nda-management', 'NDA MANAGEMENT', 14, NULL, false, NULL, 'Pending Acceptances', 'fas fa-hourglass-half'),
('/staff/nda-versions', 'nda-management', 'NDA MANAGEMENT', 14, NULL, false, NULL, 'NDA Versions', 'fas fa-file-contract'),
('/rvz/menu-access-config', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Menu Access Control', 'fas fa-key'),
('/staff/accounts/companies', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Companies', 'fas fa-city'),
('/staff/accounts/expense-categories', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Expense Categories', 'fas fa-folder'),
('/staff/accounts/hsn', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'HSN Master', 'fas fa-barcode'),
('/staff/accounts/pricing', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Pricing Config', 'fas fa-dollar-sign'),
('/staff/accounts/segments', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Segments', 'fas fa-layer-group'),
('/staff/audit-logs', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Audit Logs', 'fas fa-history'),
('/staff/departments', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Departments', 'fas fa-building'),
('/staff/partners/master', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Business Partners Config', 'fas fa-handshake'),
('/staff/settings', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Settings', 'fas fa-cog'),
('/staff/sidebar-sync', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Sidebar Sync', 'fas fa-sync-alt'),
('/staff/signup-categories', 'configuration', 'CONFIGURATION', 15, NULL, false, NULL, 'Signup Categories', 'fas fa-user-plus'),
('/rvz/real-dreams', 'real-dreams', 'ZY Property Workings', 16, 'ZY Property Workings', true, 'zynova', 'Property Amenities', 'fas fa-swimming-pool'),
('/rvz/real-dreams-dashboard', 'real-dreams', 'ZY Property Workings', 16, 'ZY Property Workings', true, 'zynova', 'Dashboard', 'fas fa-tachometer-alt'),
('/rvz/real-dreams/marketplace', 'real-dreams', 'ZY Property Workings', 16, 'ZY Property Workings', true, 'zynova', 'Property Marketplace', 'fas fa-home'),
('/rvz/real-dreams/partners', 'real-dreams', 'ZY Property Workings', 16, 'ZY Property Workings', true, 'zynova', 'Partner Profiles', 'fas fa-user-tie'),
('/rvz/real-dreams/properties', 'real-dreams', 'ZY Property Workings', 16, 'ZY Property Workings', true, 'zynova', 'Property Handler', 'fas fa-building'),
('/staff/incentives/approvals', 'zy-member-earnings', 'ZY Member Earnings', 16, 'ZY Member Earnings', true, 'zynova', 'Incentive Approvals', 'fas fa-check-circle'),
('/staff/incentives/points', 'zy-member-earnings', 'ZY Member Earnings', 16, 'ZY Member Earnings', true, 'zynova', 'MNR Points', 'fas fa-coins'),
('/staff/incentives/zynova', 'zy-member-earnings', 'ZY Member Earnings', 16, 'ZY Member Earnings', true, 'zynova', 'All Zynova Members', 'fas fa-users'),
('/staff/zynova/insurance', 'zy-member-earnings', 'ZY Member Earnings', 16, 'ZY Member Earnings', true, 'zynova', 'VGK Care (ZC)', 'fas fa-shield-alt'),
('/staff/zynova/real-estate', 'zy-member-earnings', 'ZY Member Earnings', 16, 'ZY Member Earnings', true, 'zynova', 'VGK Real Dreams (ZR)', 'fas fa-home'),
('/staff/mnr/add-packages', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Add Packages', 'fas fa-box'),
('/staff/mnr/announcements/view', 'mnr-communications', 'Announcements', 17, 'Announcements', true, 'mnr', 'Announcements View', 'fas fa-bullhorn'),
('/staff/mnr/award-management', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'Award Management', 'fas fa-medal'),
('/staff/mnr/awards-all', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'All Awards', 'fas fa-trophy'),
('/staff/mnr/awards-approval-queue', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'Awards Approval Queue', 'fas fa-list'),
('/staff/mnr/bank-all', 'mnr-approvals', 'Approvals', 17, 'Approvals', true, 'mnr', 'Bank All', 'fas fa-landmark'),
('/staff/mnr/bank-pending', 'mnr-approvals', 'Approvals', 17, 'Approvals', true, 'mnr', 'Bank Pending', 'fas fa-university'),
('/staff/mnr/banner-analytics', 'mnr-communications', 'Announcements', 17, 'Announcements', true, 'mnr', 'Banner Analytics', 'fas fa-chart-area'),
('/staff/mnr/banners-management', 'mnr-communications', 'Announcements', 17, 'Announcements', true, 'mnr', 'Banners Management', 'fas fa-image'),
('/staff/mnr/birthdays', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'Birthdays', 'fas fa-birthday-cake'),
('/staff/mnr/bonanza-claims', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'Bonanza Claims', 'fas fa-hand-holding'),
('/staff/mnr/bonanza-management', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'Bonanza Management', 'fas fa-star'),
('/staff/mnr/bulk-user-edit', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'Bulk User Edit', 'fas fa-edit'),
('/staff/mnr/change-user-password', 'mnr-security', 'Password & Security', 17, 'Password & Security', true, 'mnr', 'Change User Password', 'fas fa-key'),
('/staff/mnr/company-earnings', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Company Earnings', 'fas fa-building'),
('/staff/mnr/compliance', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Compliance', 'fas fa-clipboard-check'),
('/staff/mnr/coupon-status', 'mnr-pins', 'PINs & Approvals', 17, 'PINs & Approvals', true, 'mnr', 'Coupon Status', 'fas fa-ticket-alt'),
('/staff/mnr/daily-ceiling', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Daily Ceiling', 'fas fa-chart-line'),
('/staff/mnr/dashboard', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'Dashboard', 'fas fa-tachometer-alt'),
('/staff/mnr/data-recovery', 'mnr-data', 'Data Management', 17, 'Data Management', true, 'mnr', 'Data Recovery', 'fas fa-undo'),
('/staff/mnr/delete-management', 'mnr-data', 'Data Management', 17, 'Data Management', true, 'mnr', 'Delete Management', 'fas fa-trash-alt'),
('/staff/mnr/emergency-wallet', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Emergency Wallet', 'fas fa-exclamation-triangle'),
('/staff/mnr/expense-details', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Expense Details', 'fas fa-file-invoice-dollar'),
('/staff/mnr/expense-overview', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Expense Overview', 'fas fa-chart-bar'),
('/staff/mnr/expenses-management', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Expenses Management', 'fas fa-calculator'),
('/staff/mnr/feedback/pending', 'mnr-communications', 'Announcements', 17, 'Announcements', true, 'mnr', 'Pending Announcements', 'fas fa-comment-dots'),
('/staff/mnr/finance-supreme', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Finance Supreme', 'fas fa-chart-pie'),
('/staff/mnr/gift-wise-status', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'Gift-wise Status', 'fas fa-gift'),
('/staff/mnr/income-finance-complete', 'mnr-income', 'Income', 17, 'Income', true, 'mnr', 'Finance Complete', 'fas fa-check-double'),
('/staff/mnr/income-records', 'mnr-income', 'Income', 17, 'Income', true, 'mnr', 'Income Records', 'fas fa-chart-line'),
('/staff/mnr/income-supreme', 'mnr-income', 'Income', 17, 'Income', true, 'mnr', 'Income Supreme', 'fas fa-crown'),
('/staff/mnr/kyc-management', 'mnr-approvals', 'Approvals', 17, 'Approvals', true, 'mnr', 'KYC Management', 'fas fa-id-card'),
('/staff/mnr/menu-access-config', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Menu Access Config', 'fas fa-key'),
('/staff/mnr/menu-configuration', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Menu Configuration', 'fas fa-bars'),
('/staff/mnr/password-change', 'mnr-security', 'Password & Security', 17, 'Password & Security', true, 'mnr', 'Password Change', 'fas fa-lock'),
('/staff/mnr/payout-details', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Payout Details', 'fas fa-money-bill-wave'),
('/staff/mnr/pin-approvals', 'mnr-pins', 'PINs & Approvals', 17, 'PINs & Approvals', true, 'mnr', 'PIN Approvals', 'fas fa-key'),
('/staff/mnr/pins', 'mnr-pins', 'PINs & Approvals', 17, 'PINs & Approvals', true, 'mnr', 'PINs', 'fas fa-thumbtack'),
('/staff/mnr/procurement-queue', 'mnr-awards', 'Awards', 17, 'Awards', true, 'mnr', 'Procurement Queue', 'fas fa-shopping-cart'),
('/staff/mnr/production-reset-status', 'mnr-data', 'Data Management', 17, 'Data Management', true, 'mnr', 'Production Reset Status', 'fas fa-sync'),
('/staff/mnr/rate-configuration', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Rate Configuration', 'fas fa-percentage'),
('/staff/mnr/reactivate-reassign', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'Reactivate/Reassign', 'fas fa-redo'),
('/staff/mnr/revenue-details', 'mnr-finance', 'Finance & Compliance', 17, 'Finance & Compliance', true, 'mnr', 'Revenue Details', 'fas fa-dollar-sign'),
('/staff/mnr/role-management', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Role Management', 'fas fa-user-shield'),
('/staff/mnr/scheduler-dashboard', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'Scheduler Dashboard', 'fas fa-clock'),
('/staff/mnr/secondary-password-setup', 'mnr-security', 'Password & Security', 17, 'Password & Security', true, 'mnr', 'Secondary Password Setup', 'fas fa-shield-alt'),
('/staff/mnr/system-controls', 'mnr-config', 'System Configuration', 17, 'System Configuration', true, 'mnr', 'System Controls', 'fas fa-sliders-h'),
('/staff/mnr/user-activation-control', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'User Activation Control', 'fas fa-toggle-on'),
('/staff/mnr/user-data-search', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'User Data Search', 'fas fa-search'),
('/staff/mnr/user-update-approvals', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'User Update Approvals', 'fas fa-check'),
('/staff/mnr/user-update-controls', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'User Update Controls', 'fas fa-user-edit'),
('/staff/mnr/users', 'mnr-users', 'Users', 17, 'Users', true, 'mnr', 'Users', 'fas fa-users'),
('/staff/mnr/withdrawal-supreme', 'mnr-withdrawals', 'Withdrawals', 17, 'Withdrawals', true, 'mnr', 'Withdrawal Supreme', 'fas fa-wallet'),
('/staff/mnr/withdrawal/approvals', 'mnr-withdrawals', 'Withdrawals', 17, 'Withdrawals', true, 'mnr', 'Withdrawal Approvals', 'fas fa-check-circle'),
('/staff/mnr/withdrawal/history', 'mnr-withdrawals', 'Withdrawals', 17, 'Withdrawals', true, 'mnr', 'Withdrawal History', 'fas fa-history'),
('/staff/mnr-user/announcements', 'staff_mnr_user_announcements', 'Announcements', 18, 'Announcements', true, 'mnr-user-sidebar', 'Announcements', 'fas fa-bullhorn'),
('/staff/mnr-user/announcements/create', 'staff_mnr_user_announcements', 'Announcements', 18, 'Announcements', true, 'mnr-user-sidebar', 'Create Announcement', 'fas fa-plus'),
('/staff/mnr-user/announcements/history', 'staff_mnr_user_announcements', 'Announcements', 18, 'Announcements', true, 'mnr-user-sidebar', 'History', 'fas fa-history'),
('/staff/mnr-user/announcements/pending', 'staff_mnr_user_announcements', 'Announcements', 18, 'Announcements', true, 'mnr-user-sidebar', 'Pending Announcements', 'fas fa-hourglass-half'),
('/staff/mnr-user/audit-log', 'staff_mnr_user_system', 'Audit Log', 18, 'Audit Log', true, 'mnr-user-sidebar', 'Audit Log', 'fas fa-history'),
('/staff/mnr-user/awards/all', 'staff_mnr_user_awards', 'Awards', 18, 'Awards', true, 'mnr-user-sidebar', 'All Awards', 'fas fa-trophy'),
('/staff/mnr-user/awards/bonanza', 'staff_mnr_user_awards', 'Awards', 18, 'Awards', true, 'mnr-user-sidebar', 'Bonanza', 'fas fa-star'),
('/staff/mnr-user/coupons/available', 'staff_mnr_user_coupons', 'Coupons', 18, 'Coupons', true, 'mnr-user-sidebar', 'Available Coupons', 'fas fa-ticket-alt'),
('/staff/mnr-user/coupons/ev', 'staff_mnr_user_coupons', 'Coupons', 18, 'Coupons', true, 'mnr-user-sidebar', 'EV Coupons', 'fas fa-car'),
('/staff/mnr-user/coupons/green', 'staff_mnr_user_coupons', 'Coupons', 18, 'Coupons', true, 'mnr-user-sidebar', 'Green Coupons', 'fas fa-circle'),
('/staff/mnr-user/coupons/history', 'staff_mnr_user_coupons', 'Coupons', 18, 'Coupons', true, 'mnr-user-sidebar', 'History', 'fas fa-history'),
('/staff/mnr-user/coupons/red', 'staff_mnr_user_coupons', 'Coupons', 18, 'Coupons', true, 'mnr-user-sidebar', 'Red Coupons', 'fas fa-circle'),
('/staff/mnr-user/coupons/transfer', 'staff_mnr_user_coupons', 'Coupons', 18, 'Coupons', true, 'mnr-user-sidebar', 'Transfer', 'fas fa-exchange-alt'),
('/staff/mnr-user/create-member', 'staff_mnr_user_dashboard', 'Dashboard', 18, 'Dashboard', true, 'mnr-user-sidebar', 'Create Member', 'fas fa-user-plus'),
('/staff/mnr-user/dashboard', 'staff_mnr_user_dashboard', 'Dashboard', 18, 'Dashboard', true, 'mnr-user-sidebar', 'Dashboard', 'fas fa-tachometer-alt'),
('/staff/mnr-user/members', 'staff_mnr_user_members', 'Members', 18, 'Members', true, 'mnr-user-sidebar', 'Members', 'fas fa-users'),
('/staff/mnr-user/members/all', 'staff_mnr_user_members', 'Members', 18, 'Members', true, 'mnr-user-sidebar', 'All Members', 'fas fa-users'),
('/staff/mnr-user/members/direct', 'staff_mnr_user_members', 'Members', 18, 'Members', true, 'mnr-user-sidebar', 'Direct Members', 'fas fa-user-friends'),
('/staff/mnr-user/members/downline', 'staff_mnr_user_members', 'Members', 18, 'Members', true, 'mnr-user-sidebar', 'Downline', 'fas fa-sitemap'),
('/staff/mnr-user/members/picture', 'staff_mnr_user_members', 'Members', 18, 'Members', true, 'mnr-user-sidebar', 'Picture', 'fas fa-image'),
('/staff/mnr-user/members/ved', 'staff_mnr_user_members', 'Members', 18, 'Members', true, 'mnr-user-sidebar', 'VED Members', 'fas fa-star'),
('/staff/mnr-user/mnr/benefits', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Benefits', 'fas fa-gift'),
('/staff/mnr-user/mnr/direct', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Direct Referral', 'fas fa-user-plus'),
('/staff/mnr-user/mnr/earnings', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Earnings', 'fas fa-coins'),
('/staff/mnr-user/mnr/earnings-summary', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Earnings Summary', 'fas fa-chart-pie'),
('/staff/mnr-user/mnr/guru', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Guru Dakshina', 'fas fa-pray'),
('/staff/mnr-user/mnr/matching', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Matching', 'fas fa-handshake'),
('/staff/mnr-user/mnr/points', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Points', 'fas fa-coins'),
('/staff/mnr-user/mnr/ved', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'VED Income', 'fas fa-star'),
('/staff/mnr-user/mnr/wallet', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Wallet', 'fas fa-wallet'),
('/staff/mnr-user/mnr/withdrawals', 'staff_mnr_user_mnr', 'Earnings', 18, 'Earnings', true, 'mnr-user-sidebar', 'Withdrawals', 'fas fa-money-bill-wave'),
('/staff/mnr-user/myntreal/franchise', 'staff_mnr_user_myntreal', 'MyntReal', 18, 'MyntReal', true, 'mnr-user-sidebar', 'Franchise', 'fas fa-store'),
('/staff/mnr-user/myntreal/leads', 'staff_mnr_user_myntreal', 'MyntReal', 18, 'MyntReal', true, 'mnr-user-sidebar', 'Leads', 'fas fa-user-tie'),
('/staff/mnr-user/myntreal/properties', 'staff_mnr_user_myntreal', 'MyntReal', 18, 'MyntReal', true, 'mnr-user-sidebar', 'Properties', 'fas fa-home'),
('/staff/mnr-user/popups', 'staff_mnr_user_announcements', 'Announcements', 18, 'Announcements', true, 'mnr-user-sidebar', 'Popups', 'fas fa-window-restore'),
('/staff/mnr-user/profile', 'staff_mnr_user_dashboard', 'Dashboard', 18, 'Dashboard', true, 'mnr-user-sidebar', 'Profile', 'fas fa-user'),
('/staff/mnr-user/zynova/dashboard', 'staff_mnr_user_zynova', 'Zynova', 18, 'Zynova', true, 'mnr-user-sidebar', 'Dashboard', 'fas fa-tachometer-alt'),
('/staff/mnr-user/zynova/insurance', 'staff_mnr_user_zynova', 'Zynova', 18, 'Zynova', true, 'mnr-user-sidebar', 'Insurance', 'fas fa-shield-alt'),
('/staff/mnr-user/zynova/real-estate', 'staff_mnr_user_zynova', 'Zynova', 18, 'Zynova', true, 'mnr-user-sidebar', 'Real Estate', 'fas fa-building'),
('/staff/mnr-user/zynova/training', 'staff_mnr_user_zynova', 'Zynova', 18, 'Zynova', true, 'mnr-user-sidebar', 'Training', 'fas fa-chalkboard-teacher'),
('/staff/zynova/purchase-orders', 'zy-member-earnings', 'Zynova Mobility EV', 16, 'Zynova Mobility EV', true, 'zynova', 'EV Spares PO Management', 'fas fa-shopping-cart'),
('/staff/marketplace-config', 'zy-member-earnings', 'Zynova Mobility EV', 16, 'Zynova Mobility EV', true, 'zynova', 'Marketplace Config', 'fas fa-cog'),
('/staff/zynova/etc-students', 'zy-member-earnings', 'Zynova Mobility EV', 16, 'Zynova Mobility EV', true, 'zynova', 'ETC Student Master', 'fas fa-user-graduate');
