const STAFF_PAGES = [
  { path: '/staff/dashboard', name: 'Staff Dashboard', requiresAuth: true },
  { path: '/staff/my-attendance', name: 'My Attendance', requiresAuth: true },
  { path: '/staff/my-journeys', name: 'My Journeys', requiresAuth: true },
  { path: '/staff/my-timesheet', name: 'My Timesheet', requiresAuth: true },
  { path: '/staff/my-kras', name: 'My KRAs', requiresAuth: true },
  { path: '/staff/my-location-history', name: 'My Location History', requiresAuth: true },
  { path: '/staff/my-kyc', name: 'My KYC', requiresAuth: true },
  { path: '/staff/tasks/assigned-to-me', name: 'Tasks Assigned To Me', requiresAuth: true },
  { path: '/staff/tasks/assigned-by-me', name: 'Tasks Assigned By Me', requiresAuth: true },
  { path: '/staff/settings', name: 'Staff Settings', requiresAuth: true },
  { path: '/staff/change-password', name: 'Change Password', requiresAuth: true },
  { path: '/staff/2fa-settings', name: '2FA Settings', requiresAuth: true },
  { path: '/staff/team/attendance', name: 'Team Attendance', requiresAuth: true },
  { path: '/staff/team/journeys', name: 'Team Journeys', requiresAuth: true },
  { path: '/staff/team/activities', name: 'Team Activities', requiresAuth: true },
  { path: '/staff/team/attendance-summary', name: 'Team Attendance Summary', requiresAuth: true },
  { path: '/staff/team/location-tracker', name: 'Team Location Tracker', requiresAuth: true },
  { path: '/staff/all-journeys', name: 'All Journeys', requiresAuth: true },
  { path: '/staff/vgk4u-journeys', name: 'VGK4U Journeys', requiresAuth: true },
  { path: '/staff/attendance-computation', name: 'Attendance Computation', requiresAuth: true },
  { path: '/staff/attendance-reports', name: 'Attendance Reports', requiresAuth: true },
  { path: '/staff/attendance-sheet', name: 'Attendance Sheet', requiresAuth: true },
  { path: '/staff/task-tracker', name: 'Task Tracker', requiresAuth: true },
  { path: '/staff/task-review', name: 'Task Review', requiresAuth: true },
  { path: '/staff/kra-templates', name: 'KRA Templates', requiresAuth: true },
  { path: '/staff/kra-review', name: 'KRA Review', requiresAuth: true },
  { path: '/staff/kra-tracking-sheet', name: 'KRA Tracking Sheet', requiresAuth: true },
  { path: '/staff/timesheet-approval', name: 'Timesheet Approval', requiresAuth: true },
  { path: '/staff/manager-review', name: 'Manager Review', requiresAuth: true },
  { path: '/staff/employees', name: 'Employees List', requiresAuth: true },
  { path: '/staff/employee-directory', name: 'Employee Directory', requiresAuth: true },
  { path: '/staff/departments', name: 'Departments', requiresAuth: true },
  { path: '/staff/audit-logs', name: 'Audit Logs', requiresAuth: true },
  { path: '/staff/kyc-approvals', name: 'KYC Approvals', requiresAuth: true },
  { path: '/staff/nda-editor', name: 'NDA Editor', requiresAuth: true },
  { path: '/staff/nda-versions', name: 'NDA Versions', requiresAuth: true },
  { path: '/staff/nda-pending', name: 'NDA Pending', requiresAuth: true },
  { path: '/staff/nda-acceptance-audit', name: 'NDA Acceptance Audit', requiresAuth: true },
  { path: '/staff/accounts/companies', name: 'SFMS Companies', requiresAuth: true },
  { path: '/staff/accounts/income-entries', name: 'SFMS Income Entries', requiresAuth: true },
  { path: '/staff/accounts/expense-entries', name: 'SFMS Expense Entries', requiresAuth: true },
  { path: '/staff/accounts/fund-allocations', name: 'SFMS Fund Allocations', requiresAuth: true },
  { path: '/staff/accounts/party-ledger', name: 'SFMS Party Ledger', requiresAuth: true },
  { path: '/staff/accounts/receivables', name: 'SFMS Receivables', requiresAuth: true },
  { path: '/staff/accounts/payables', name: 'SFMS Payables', requiresAuth: true },
  { path: '/staff/accounts/balance-sheet', name: 'SFMS Balance Sheet', requiresAuth: true },
  { path: '/staff/accounts/reports', name: 'SFMS Reports', requiresAuth: true },
  { path: '/staff/accounts/hsn', name: 'SFMS HSN Codes', requiresAuth: true },
  { path: '/staff/accounts/vendors', name: 'SFMS Vendors', requiresAuth: true },
  { path: '/staff/accounts/stock-items', name: 'SFMS Stock Items', requiresAuth: true },
  { path: '/staff/accounts/purchase-invoices', name: 'SFMS Purchase Invoices', requiresAuth: true },
  { path: '/staff/accounts/sales-invoices', name: 'SFMS Sales Invoices', requiresAuth: true },
  { path: '/staff/accounts/bom', name: 'SFMS BOM', requiresAuth: true },
  { path: '/staff/accounts/manufacturing', name: 'SFMS Manufacturing', requiresAuth: true },
  { path: '/staff/accounts/procurement', name: 'SFMS Procurement', requiresAuth: true },
  { path: '/staff/accounts/pricing', name: 'SFMS Pricing', requiresAuth: true },
  { path: '/staff/accounts/segments', name: 'SFMS Segments', requiresAuth: true },
  { path: '/staff/inventory/stock-ledger', name: 'Stock Ledger', requiresAuth: true },
  { path: '/staff/inventory/stock-transfers', name: 'Stock Transfers', requiresAuth: true },
];

const RVZ_PAGES = [
  { path: '/rvz/dashboard', name: 'RVZ Dashboard', requiresAuth: true },
  { path: '/rvz/user-data-search', name: 'User Data Search', requiresAuth: true },
  { path: '/rvz/brand-level-management', name: 'Brand Level Management', requiresAuth: true },
  { path: '/rvz/popup-control', name: 'Popup Control', requiresAuth: true },
  { path: '/rvz/terms-conditions-management', name: 'T&C Management', requiresAuth: true },
  { path: '/rvz/terms-conditions-audit', name: 'T&C Audit', requiresAuth: true },
  { path: '/rvz/bulk-user-edit', name: 'Bulk User Edit', requiresAuth: true },
  { path: '/rvz/user-activation-control', name: 'User Activation Control', requiresAuth: true },
  { path: '/rvz/withdrawal/dashboard', name: 'Withdrawal Dashboard', requiresAuth: true },
  { path: '/rvz/user-update-controls', name: 'User Update Controls', requiresAuth: true },
  { path: '/rvz/reactivate-reassign', name: 'Reactivate/Reassign', requiresAuth: true },
  { path: '/rvz/user-update-approvals', name: 'User Update Approvals', requiresAuth: true },
  { path: '/rvz/change-user-password', name: 'Change User Password', requiresAuth: true },
  { path: '/rvz/password-change', name: 'RVZ Password Change', requiresAuth: true },
  { path: '/rvz/secondary-password-setup', name: 'Secondary Password Setup', requiresAuth: true },
  { path: '/rvz/add-packages', name: 'Add Packages', requiresAuth: true },
  { path: '/rvz/role-management', name: 'Role Management', requiresAuth: true },
  { path: '/rvz/system-controls', name: 'System Controls', requiresAuth: true },
  { path: '/rvz/rate-configuration', name: 'Rate Configuration', requiresAuth: true },
  { path: '/rvz/daily-ceiling', name: 'Daily Ceiling', requiresAuth: true },
  { path: '/rvz/emergency-wallet', name: 'Emergency Wallet', requiresAuth: true },
  { path: '/rvz/menu-configuration', name: 'Menu Configuration', requiresAuth: true },
  { path: '/rvz/menu-access-config', name: 'Menu Access Control', requiresAuth: true },
  { path: '/rvz/scheduler-dashboard', name: 'Scheduler Dashboard', requiresAuth: true },
  { path: '/rvz/income-supreme', name: 'Income Supreme', requiresAuth: true },
  { path: '/rvz/income-history-supreme', name: 'Income History Supreme', requiresAuth: true },
  { path: '/rvz/award-management', name: 'Award Management', requiresAuth: true },
  { path: '/rvz/department-management', name: 'Department Management', requiresAuth: true },
  { path: '/rvz/crm', name: 'CRM Leads', requiresAuth: true, expectedSelector: '#leadsTable, .crm-dashboard' },
  { path: '/rvz/real-dreams', name: 'Real Dreams Dashboard', requiresAuth: true, expectedSelector: '.real-dreams-dashboard, .company-card' },
  { path: '/rvz/real-dreams/properties', name: 'Real Dreams Properties', requiresAuth: true, expectedSelector: '.properties-table, .property-card' },
  { path: '/rvz/real-dreams/partners', name: 'Real Dreams Partners', requiresAuth: true, expectedSelector: '.partners-table, .partner-card' },
  { path: '/staff/signup-categories', name: 'Signup Categories', requiresAuth: true, expectedSelector: '.categories-table' },
];

const PARTNER_PAGES = [
  { path: '/partner/orders', name: 'Partner Orders', requiresAuth: true },
  { path: '/partner/master', name: 'Partner Master', requiresAuth: true },
  { path: '/partner/pricing', name: 'Partner Pricing', requiresAuth: true },
  { path: '/partner/payments', name: 'Partner Payments', requiresAuth: true },
  { path: '/partner/invoices', name: 'Partner Invoices', requiresAuth: true },
  { path: '/partner/dispatch', name: 'Partner Dispatch', requiresAuth: true },
  { path: '/partner/order-routing', name: 'Order Routing', requiresAuth: true },
  { path: '/partner/order-approval', name: 'Order Approval', requiresAuth: true },
  { path: '/order-fulfillment-dashboard', name: 'Order Fulfillment Dashboard', requiresAuth: true },
];

const USER_PAGES = [
  { path: '/dashboard', name: 'User Dashboard', requiresAuth: true },
  { path: '/user/awards', name: 'User Awards', requiresAuth: true },
  { path: '/user/field-allowances', name: 'Field Allowances', requiresAuth: true },
  { path: '/user/direct-referral', name: 'Direct Referral', requiresAuth: true },
  { path: '/user/matching-referral', name: 'Matching Referral', requiresAuth: true },
  { path: '/user/guru-dakshina', name: 'Guru Dakshina', requiresAuth: true },
];

const PUBLIC_PAGES = [
  { path: '/', name: 'Home/Login', requiresAuth: false },
  { path: '/login', name: 'User Login', requiresAuth: false },
  { path: '/staff/login', name: 'Staff Login', requiresAuth: false },
  { path: '/real-dreams/marketplace', name: 'Real Dreams Marketplace', requiresAuth: false },
];

const ADMIN_PAGES = [
  { path: '/admin/kyc-management', name: 'KYC Management', requiresAuth: true },
  { path: '/admin/birthdays', name: 'Birthday Details', requiresAuth: true },
  { path: '/admin/unified-approval-system', name: 'Pending Approvals', requiresAuth: true },
  { path: '/admin/members/search', name: 'Search Members', requiresAuth: true },
  { path: '/admin/delete-management', name: 'Delete Management', requiresAuth: true },
  { path: '/admin/data-recovery', name: 'Data Recovery', requiresAuth: true },
  { path: '/admin/income-pending', name: 'Income Pending', requiresAuth: true },
  { path: '/admin/income-verified', name: 'Income Verified', requiresAuth: true },
];

module.exports = {
  STAFF_PAGES,
  RVZ_PAGES,
  PARTNER_PAGES,
  USER_PAGES,
  PUBLIC_PAGES,
  ADMIN_PAGES,
  ALL_PAGES: [...PUBLIC_PAGES, ...STAFF_PAGES, ...RVZ_PAGES, ...PARTNER_PAGES, ...USER_PAGES, ...ADMIN_PAGES]
};
